dbt_databricks:
  target: dev
  outputs:
    dev:
      type: databricks
      catalog: "{{ env_var('DBT_CATALOG', 'databricks-dbt') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'default') }}"
      host: "{{ env_var('DBT_HOST') }}"
      http_path: "{{ env_var('DBT_HTTP_PATH') }}"
      token: "{{ env_var('DBT_TOKEN') }}"
      threads: 1